# Generated by Django 2.1.2 on 2018-11-06 13:15

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='photo',
            field=imagekit.models.fields.ProcessedImageField(upload_to='uploads/gallery/images', verbose_name='photo'),
        ),
    ]
