# Generated by Django 2.1.2 on 2018-11-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20181106_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='date_created',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='image',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='date updated'),
        ),
        migrations.AlterField(
            model_name='image',
            name='uuid',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='image uuid'),
        ),
    ]
